version: "1"

services:

  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation
    ports:
      - 8000:8000
    volumes:
      - ./:/src
    entrypoint:
      - python
