#!/usr/bin/env bash

set -x
set -e

PREFIX=''

[[ -z "$GITHUB_ACTIONS" ]] && PREFIX='docker compose run --rm --no-deps python -m' 

${PREFIX} flake8 project_name/ test/
${PREFIX} pydocstyle project_name/
